### ISSUE TITLE
Should I move from acts_as_tenant to Apartment?

### ISSUE THREAD

**Issue by gvn182** [rails-on-services/apartment#104]
Hi folks, I've been using acts_as_tenant for a while, it uses column scoping for tenancy. I have around 350 customers and as the tables are getting bigger, I'm starting to face performance issues.

When I first saw this gem and saw the possibility to apply tenancy by different schemas I became very interested.

Digging further into the issues, I discovered this fork and this post (https://influitive.io/our-multi-tenancy-journey-with-postgres-schemas-and-apartment-6ecda151a21f) and now I'm worried if it's gonna fulfill my needs.

I see that it has the possibility to apply tenancy by schemas and databases, what are you guys using? what is the best option?

I have around 100 tables and 350 customers/accounts, what's your use case? is it working well?

Thanks.

**Comment by rpbaltazar** [comment]
In our current use case, in production we have ~ 40 tenants and 200 tables and at the moment our current bottleneck is not the database.
Looking at the article of why influitive abandoned apartment, I believe a few things have changed since.

Migrations - this is still true. The more schemas (tenants) we have, the slower the migrations run because they iterate over all tenants. in our deploy process, so far, we are not deeply affected by this. We deploy to staging multiple times a day and to production almost daily, sometimes more than once.
Database Resources - we run in db.r5.8xlarge writer and db.r5.4xlarge reader. That actually represents a downscale from what it used to be, since we've been doing a lot of performance cleanup.
Client Memory Bloat - I believe this has mostly been fixed with rails 6 schema cache. we were facing this problem and had implemented our solution of this, but we have not faced it since rails 6 upgrade.
Record Identification - This is, in my opinion a not real issue. They had the problem because they were using ids and that could have been solved (as they point out as well) using uuids. In our case, it is important that we don't accidentally share data across tenants, so having schemas as separation works well for us.

Finally, I've read an article that i think it touches a lot of good points and its worth the read:
https://blog.arkency.com/comparison-of-approaches-to-multitenancy-in-rails-apps/
