### ISSUE TITLE
Is Apartment::Reloader still necessary?

### ISSUE THREAD

**Issue by fsateler** [rails-on-services/apartment#151]
The comment in railtie.rb says:

> The following initializers are a workaround to the fact that I can't properly hook into the rails reloader

But this is no longer (was it ever?) true: we have (and use) `to_prepare`. Maybe it is no longer necessary?

**Comment by marcelolx** [comment]
@fsateler I think the reason is better explained here https://github.com/rails-on-services/apartment/blob/development/lib/apartment/reloader.rb#L8, as I understood it, this is necessary to reload apartment only after the files are reloaded.

But I think maybe now there is a proper way to hook into the reload process after the files are reloaded, looking at the [Reloader docs](https://rdoc.info/github/rails/rails/ActiveSupport/Reloader) I think the `to_complete` callback would fit well for this problem 🤔 This functionality was added by this PR https://github.com/rails/rails/pull/23807

**Comment by fsateler** [comment]
AFAICT, to_prepare is invoked after the code has been reloaded: https://github.com/rails/rails/blob/main/activesupport/lib/active_support/reloader.rb#L58

**Comment by marcelolx** [comment]
Sorry I miss that part 😄 Maybe this isn't really necessary anymore.

**Comment by rpbaltazar** [comment]
so, what you're suggesting, @fsateler is to completely remove the Reloader and move the console requiring to `to_prepare` if in development? 
That seems relatively safe for me to test in our app because it should at most affect the development environment and should be relatively simple to spot.
I'll create a branch with those changes and try it out.

**Comment by fsateler** [comment]
Indeed, that's what I think. But I asked because maybe there is some weird interaction I'm not aware of...

**Comment by rpbaltazar** [comment]
> Indeed, that's what I think. But I asked because maybe there is some weird interaction I'm not aware of...

None that I know of either. I'll create the branch and run our develop env against it. Suggest you do the same on your end @fsateler and @marcelolx to see if any of our envs breaks under those conditions

**Comment by rpbaltazar** [comment]
Opened the draft PR. Things on my end seem to be working the same way. Will run my dev env for a few days with this branch but for now looks ok

**Comment by fsateler** [comment]
Thanks! will try it now

**Comment by otagi** [comment]
With 2.11.0, the [console.rb](https://github.com/rails-on-services/apartment/blob/development/lib/apartment/console.rb) helpers are not available in the rails console anymore. They are back if I downgrade to 2.9.0.

```
irb(main):001:0> st
(irb):1:in `<main>': undefined local variable or method `st' for main:Object (NameError)
```

Is it related to this change? Should the helpers be loaded manually now?

(ruby 3.0.3, rails 6.1.4.6)
