### ISSUE TITLE
Questions about dependent gem tables

### ISSUE THREAD

**Issue by kapso** [rails-on-services/apartment#165]
We have a `Company` model that we want to replicate in other schemas. For this model, we also use Friendly ID gem (https://github.com/norman/friendly_id) for generating slugs. So whenever the `name` of the company is updated, a new record is written to a `friendly_id_slugs` table

In the following scenario...

```ruby
Apartment::Tenant.switch('snapshot') do
  Company.where(id: 1).update(name: "new name")
end
```

- which schema (we are on Postgres) will the Apartment use for writing to `friendly_id_slugs`, -- `public` or `snapshot`?

Ideally, we want `public.friendly_id_slugs` to be used for writing to the table.

**Comment by rpbaltazar** [comment]
Assuming that if you `use: :history` will base the search on the friendly_id_slugs table and not the slug attribute added to the model, you should be able to add `FriendlyId::Slug` class to the apartment configuration `excluded_models`. 
This way, when adding the record it will go to public.

There is a potential issue when looking for the record from the slug. Unless you're already in the right tenant, you won't be able to find the record from the slug.
let's say you have your described scenario:

Tenants: public and snapshot

in snapshot you have company id 1
in public you have no companies

when you run 
```
Apartment::Tenant.switch('snapshot') do
  Company.where(id: 1).update(name: "new name")
end
```

this will create the friendly id slug in the public.friendly_id_slugs as you want. let's call it `new name` for now.
This record will look like:

```csv
id, slug, sluggable_id, sluggable_type, scope, created_at  
1, new name, 1, Company, , 2021-07-05 03:19:16.474909
```

but then in a different connection (or opening a new console), if you try to do

```
Company.friendly.find('new name')
```
without actually switching the tenant, you won't be able to find the record. or potentially worse, if you also have a company id 1 in the public schema, you'd be getting that record instead of the one you want.

You can probalby work around this friendly_id gem to store the tenant in the scope and switch to the right tenant before looking for the record. This obviously assumes that your slug names are unique.
