### ISSUE TITLE
Maintenance and Future Updates Support?

### ISSUE THREAD

**Issue by vinayuttam** [rails-on-services/apartment#222]
Do we know if there's going to any maintenance and future updates? It's been more than an year since the last release in Feb 2022.

**Comment by samuelpares** [comment]
Yeah, I would love to here about it too

**Comment by rpbaltazar** [comment]
Hi everyone! I think i have mentioned this in some other thread. I have since moved from working with a project that I could use to test all the updates and from rails itself so it'll be extremely hard for me to actively maintain this project.

I'm more than happy to pass the ownership to someone who can be more committed to this.
Feel free to reach me out on my email to discuss about ownership transferring plan.

**Comment by kapso** [comment]
@rpbaltazar do you know if there are any other similar projects?

**Comment by hoshy** [comment]
> @rpbaltazar do you know if there are any other similar projects?

@kapso https://github.com/markets/awesome-ruby#ormodm-extensions => Multi-tenancy

**Comment by rpbaltazar** [comment]
After quite some time waiting for people to volunteer, there have been some people reaching out to me asking to take the ownership of the gem.
I've added most of them to the user group.
@riggleg @mnovelo @IanMcNelly will be handling this moving forward! :)
