### ISSUE TITLE
Release a new version that supports Rails 7.1

### ISSUE THREAD

**Issue by evmorov** [rails-on-services/apartment#249]
Hello, I don't want to be annoying, but I'm curious about when a new version will be released. Previously, it was stated [here](https://github.com/rails-on-services/apartment/issues/245):

> once it's more stable we'll cut a release

It has been a month since then. Is it more stable now?

**Comment by mnovelo** [comment]
We'd like to get the build pipeline to work (ideally via GitHub Action) and for the specs to pass before cutting a new version. Any help would be appreciated!

**Comment by andyundso** [comment]
I could help with the testing pipeline on GitHub Actions. I built a testing pipeline also with Appraisal against different Rails and Ruby versions over at https://github.com/simplificator/keycloak_oauth/blob/main/.github/workflows/tests.yml.

From what I can see, we would likely need to test the different combinations of:

- Postgres / MySQL
- Rails 6.1, 7.0, 7.1
- Ruby 3.0, 3.1, 3.3 + JRuby 9.4.6.0 or newer (equals CRuby 3.1)

regarding MySQL: will you still support 5.7 (end of life since October 2023) or only 8.0+? what about MariaDB?

**Comment by mnovelo** [comment]
Wow thank you so much @andyundso!

Re: MySQL, I don't work with it myself and have no means to test it in production, but if 5.7 is past its EOL, let's drop it. We'll only support MariaDB if someone is able to add it and help support it [like has been started for trilogy](https://github.com/rails-on-services/apartment/pull/247)

**Comment by andyundso** [comment]
well, then #250 should contain everything needed.

it just tests one version of Postgres (v14, since the Ubuntu Runner on GitHub Actions ships with the v14 version of the Postgres client). Also, the JRuby tests fail currently, not sure if those should be skipped for now or you want to merge the PR as-is.

**Comment by mrpasquini** [comment]
I tracked down the jruby issues in today and added them to https://github.com/rails-on-services/apartment/pull/251

**Comment by IanMcNelly** [comment]
Merging #251 to resolve this issue because it has passing tests, parity for rails/ruby version coverage to #250, and doesn't introduce a new gem. The fix for the tests in JRuby is good from my point of view; since we're manipulating the resulting strings, we would never want the double quotes to be present

**Comment by IanMcNelly** [comment]
Reopening until the release is actually available!

**Comment by mnovelo** [comment]
Released! https://rubygems.org/gems/ros-apartment
