### ISSUE TITLE
How to configure use_schema_cache_dump with ros-apartment gem?

### ISSUE THREAD

**Issue by rohangrg** [rails-on-services/apartment#274]
We are using apartment gem, and recently we changed our passenger config to restart a process whenever it hits request count of 400. 

```
SELECT a.attname
FROM (  SELECT indrelid, indkey, generate_subscripts(  indkey, $1) idx
    FROM pg_index
    WHERE indrelid  = $2::regclass
AND  indisprimary  ) i  JOIN  pg_attribute a  ON a.attrelid  = i.indrelid  AND a.attnum =  i.indkey[i.idx]  ORDER BY i.idx
```
 Due to which, the above query is getting called multiple times, which is called whenever the process is started/restarted.
 
 I read some post online  [Issue URL](https://gitlab.com/gitlab-org/gitlab/-/issues/325608) and found out that this can be avoided if enabled use_schema_cache_dump in my rails application. Solution they suggested [Solution](https://blog.saeloun.com/2020/03/18/rails-schema-cache-path-config)
 
 But will it work with ros-apartment gem? Since each tenant can have different schema.

**Comment by mnovelo** [comment]
So we've been using the schema cache dump successfully with Apartment because **each tenant has the exact same schema**. It's been my understanding that an invariant of the Apartment gem was that each tenant has the same schema. Even models that should only be used on the public tenant are created on all tenants so that the `schema.rb` file applies to all tenants. How are you currently handling the schema.rb file not applying to all tenants?

**Comment by rohangrg** [comment]
Yes, you are correct, schema is the same.

What I meant was if schema_cache.yml file is related to data in tenants or not. Just was curious to know about it before implementing it since I have not seen any single article of using use_schema_cache_dump with ros-apartment gem.

Thanks, if you are already using it without any issue, will go ahead with it.
